[build]
  # Build command (optional - can be used for processing)
  command = "npm run build"
  
  # Publish directory (where your built files are located)
  publish = "."
  
  # Functions directory (if you add serverless functions later)
  # functions = "functions"

[build.environment]
  # Environment variables if needed
  # NODE_VERSION = "18"

[[redirects]]
  # Handle single page app routing if needed
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers are optional for portfolio sites
# Uncomment the section below if you need strict security headers
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "SAMEORIGIN"
#     X-XSS-Protection = "1; mode=block"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
